//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes_CredentialAgentRelationship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Codes_CredentialAgentRelationship()
        {
            this.Entity_AgentRelationship = new HashSet<Entity_AgentRelationship>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string SchemaTag { get; set; }
        public string ReverseRelation { get; set; }
        public string ReverseSchemaTag { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsQARole { get; set; }
        public Nullable<bool> IsOwnerAgentRole { get; set; }
        public Nullable<bool> IsAgentToAgentRole { get; set; }
        public Nullable<bool> IsEntityToAgentRole { get; set; }
        public Nullable<bool> IsAssessmentAgentRole { get; set; }
        public Nullable<bool> IsLearningOppAgentRole { get; set; }
        public Nullable<int> Totals { get; set; }
        public Nullable<int> CredentialTotals { get; set; }
        public Nullable<int> OrganizationTotals { get; set; }
        public Nullable<int> AssessmentTotals { get; set; }
        public Nullable<int> LoppTotals { get; set; }
        public Nullable<int> QAPerformedTotals { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_AgentRelationship> Entity_AgentRelationship { get; set; }
    }
}
