//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptScheme_Concept
    {
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public int ConceptSchemeId { get; set; }
        public string PrefLabel { get; set; }
        public string Definition { get; set; }
        public string CTID { get; set; }
        public string Notation { get; set; }
        public Nullable<bool> IsTopConcept { get; set; }
        public Nullable<int> BroaderConceptId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int LastUpdatedById { get; set; }
        public string Note { get; set; }
        public string SubjectWebpage { get; set; }
        public string Properties { get; set; }
    
        public virtual ConceptScheme ConceptScheme { get; set; }
    }
}
