//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counts_CostManifest_Property
    {
        public int Id { get; set; }
        public string Property { get; set; }
        public string Label { get; set; }
        public string Policy { get; set; }
        public string PropertyGroup { get; set; }
        public int Total { get; set; }
        public decimal PercentOfOverallTotal { get; set; }
    }
}
