//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counts_EntityStatistic
    {
        public int Id { get; set; }
        public int EntityTypeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SchemaName { get; set; }
        public Nullable<int> Totals { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Codes_EntityTypes Codes_EntityTypes { get; set; }
    }
}
