//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class CredentialingAction
    {
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public string CTID { get; set; }
        public int EntityStateId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid ActingAgentUid { get; set; }
        public Nullable<int> ActionStatusTypeId { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string EvidenceOfAction { get; set; }
        public string ResultingAward { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string Object { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Codes_CredentialingActionType Codes_CredentialingActionType { get; set; }
        public virtual Codes_PropertyValue Codes_PropertyValue { get; set; }
    }
}
