//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataProfile_QuantitativeValue
    {
        public int Id { get; set; }
        public int DataProfileId { get; set; }
        public string PropertyName { get; set; }
        public Nullable<int> UnitTypeId { get; set; }
        public string UnitText { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public string Description { get; set; }
        public System.Guid RowId { get; set; }
        public string DelimitedSummary { get; set; }
    }
}
