//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationFramework
    {
        public int Id { get; set; }
        public string FrameworkName { get; set; }
        public string CTID { get; set; }
        public string FrameworkUri { get; set; }
        public string SourceUrl { get; set; }
        public string FrameworkUrl { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> ExistsInRegistry { get; set; }
        public string OrganizationCTID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string CredentialRegistryId { get; set; }
        public int EntityStateId { get; set; }
    }
}
