//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_FrameworkItem
    {
        public int Id { get; set; }
        public int EntityId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CodeGroup { get; set; }
        public string CodedNotation { get; set; }
        public string Name { get; set; }
        public string TargetNode { get; set; }
        public Nullable<bool> IsOtherFramework { get; set; }
        public Nullable<int> ExternalFrameworkId { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
