//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_VerificationProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entity_VerificationProfile()
        {
            this.Entity_VerificationStatus = new HashSet<Entity_VerificationStatus>();
        }
    
        public int Id { get; set; }
        public int EntityId { get; set; }
        public string Description { get; set; }
        public string SubjectWebpage { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public Nullable<bool> HolderMustAuthorize { get; set; }
        public string VerificationService { get; set; }
        public string VerificationDirectory { get; set; }
        public string VerificationMethodDescription { get; set; }
        public Nullable<System.Guid> OfferedByAgentUid { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.Guid RowId { get; set; }
    
        public virtual Entity Entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_VerificationStatus> Entity_VerificationStatus { get; set; }
    }
}
