//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_ReferenceConnection
    {
        public int Id { get; set; }
        public int EntityReferenceId { get; set; }
        public System.Guid EntityUid { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Entity_Reference Entity_Reference { get; set; }
    }
}
