//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_IdentifierValue
    {
        public int Id { get; set; }
        public int EntityId { get; set; }
        public int IdentityValueTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IdentifierType { get; set; }
        public string IdentifierValueCode { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
