//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_Reference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entity_Reference()
        {
            this.Entity_ReferenceConnection = new HashSet<Entity_ReferenceConnection>();
        }
    
        public int Id { get; set; }
        public int EntityId { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string TextValue { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> PropertyValueId { get; set; }
    
        public virtual Entity Entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_ReferenceConnection> Entity_ReferenceConnection { get; set; }
        public virtual Codes_PropertyValue Codes_PropertyValue { get; set; }
    }
}
