//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_ProcessProfile
    {
        public int Id { get; set; }
        public int EntityId { get; set; }
        public Nullable<int> ProcessTypeId { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string Description { get; set; }
        public string SubjectWebpage { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public Nullable<System.Guid> ProcessingAgentUid { get; set; }
        public string ProcessFrequency { get; set; }
        public string ProcessMethod { get; set; }
        public string ProcessMethodDescription { get; set; }
        public string ScoringMethodDescription { get; set; }
        public string ScoringMethodExample { get; set; }
        public string ScoringMethodExampleDescription { get; set; }
        public string ProcessStandards { get; set; }
        public string ProcessStandardsDescription { get; set; }
        public string VerificationMethodDescription { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Codes_ProcessProfileType Codes_ProcessProfileType { get; set; }
    }
}
