//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_Cache
    {
        public int Id { get; set; }
        public int EntityTypeId { get; set; }
        public string EntityType { get; set; }
        public System.Guid EntityUid { get; set; }
        public Nullable<int> EntityStateId { get; set; }
        public string CTID { get; set; }
        public Nullable<int> parentEntityId { get; set; }
        public Nullable<System.Guid> parentEntityUid { get; set; }
        public string parentEntityType { get; set; }
        public Nullable<int> parentEntityTypeId { get; set; }
        public int BaseId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SubjectWebpage { get; set; }
        public Nullable<int> OwningOrgId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> CacheDate { get; set; }
        public Nullable<int> PublishedByOrgId { get; set; }
        public string ResourceDetail { get; set; }
        public string AgentRelationshipsForEntity { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
