//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_AggregateDataProfile
    {
        public int Id { get; set; }
        public int EntityId { get; set; }
        public System.Guid RowId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DateEffective { get; set; }
        public string Source { get; set; }
        public Nullable<int> LowEarnings { get; set; }
        public Nullable<int> MedianEarnings { get; set; }
        public Nullable<int> HighEarnings { get; set; }
        public Nullable<int> PostReceiptMonths { get; set; }
        public string DemographicInformation { get; set; }
        public string JobsObtainedJson { get; set; }
        public Nullable<int> NumberAwarded { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string Currency { get; set; }
        public string ExpirationDate { get; set; }
        public string FacultyToStudentRatio { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
