//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_DurationProfile
    {
        public int Id { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> FromYears { get; set; }
        public Nullable<int> FromMonths { get; set; }
        public Nullable<int> FromWeeks { get; set; }
        public Nullable<int> FromDays { get; set; }
        public Nullable<int> FromHours { get; set; }
        public Nullable<int> FromMinutes { get; set; }
        public Nullable<int> ToYears { get; set; }
        public Nullable<int> ToMonths { get; set; }
        public Nullable<int> ToWeeks { get; set; }
        public Nullable<int> ToDays { get; set; }
        public Nullable<int> ToHours { get; set; }
        public Nullable<int> ToMinutes { get; set; }
        public string DurationComment { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public string FromDuration { get; set; }
        public string ToDuration { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> AverageMinutes { get; set; }
        public string DurationSummary { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
