//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import_Staging
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Import_Staging()
        {
            this.Import_Message = new HashSet<Import_Message>();
        }
    
        public int Id { get; set; }
        public string EnvelopeId { get; set; }
        public int EntityTypedId { get; set; }
        public string Ctid { get; set; }
        public System.DateTime DownloadDate { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DocumentUpdatedAt { get; set; }
        public string ResourcePublicKey { get; set; }
        public string Payload { get; set; }
        public Nullable<bool> IsMostRecentDownload { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Import_Message> Import_Message { get; set; }
    }
}
