//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import_EntityResolution
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ReferencedId { get; set; }
        public string ReferencedCtid { get; set; }
        public Nullable<int> ReferencedEntityTypeId { get; set; }
        public Nullable<System.Guid> EntityUid { get; set; }
        public Nullable<bool> IsResolved { get; set; }
        public Nullable<int> EntityBaseId { get; set; }
    }
}
