//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageLog
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public string Application { get; set; }
        public string Activity { get; set; }
        public string MessageType { get; set; }
        public string Message { get; set; }
        public string Description { get; set; }
        public Nullable<int> ActionByUserId { get; set; }
        public string ActivityObjectId { get; set; }
        public string RelatedUrl { get; set; }
        public string SessionId { get; set; }
        public string IPAddress { get; set; }
        public string Tags { get; set; }
    }
}
