//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupationProfile
    {
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int EntityStateId { get; set; }
        public string CTID { get; set; }
        public string SubjectWebpage { get; set; }
        public string AbilityEmbodied { get; set; }
        public string Classification { get; set; }
        public string CodedNotation { get; set; }
        public string Comment { get; set; }
        public string Identifier { get; set; }
        public string KnowledgeEmbodied { get; set; }
        public string SkillEmbodied { get; set; }
        public string SameAs { get; set; }
        public string VersionIdentifier { get; set; }
        public string JsonProperties { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
