//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupationProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OccupationProfile()
        {
            this.Entity_Occupation = new HashSet<Entity_Occupation>();
        }
    
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int EntityStateId { get; set; }
        public string CTID { get; set; }
        public string SubjectWebpage { get; set; }
        public string AbilityEmbodied { get; set; }
        public string Classification { get; set; }
        public string CodedNotation { get; set; }
        public string Comment { get; set; }
        public string Identifier { get; set; }
        public string KnowledgeEmbodied { get; set; }
        public string SkillEmbodied { get; set; }
        public string SameAs { get; set; }
        public string VersionIdentifier { get; set; }
        public string JsonProperties { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.Guid> PrimaryAgentUID { get; set; }
        public string AlternateName { get; set; }
        public string EnvironmentalHazardType { get; set; }
        public string PerformanceLevelType { get; set; }
        public string PhysicalCapabilityType { get; set; }
        public string SensoryCapabilityType { get; set; }
        public string Keyword { get; set; }
        public string TargetCompetency { get; set; }
        public int LifeCycleStatusTypeId { get; set; }
        public string InCatalog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_Occupation> Entity_Occupation { get; set; }
    }
}
