//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pathway
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pathway()
        {
            this.Entity_HasPathway = new HashSet<Entity_HasPathway>();
        }
    
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public string CTID { get; set; }
        public string Name { get; set; }
        public Nullable<int> EntityStateId { get; set; }
        public string Description { get; set; }
        public string SubjectWebpage { get; set; }
        public Nullable<System.Guid> OwningAgentUid { get; set; }
        public string HasProgressionModel { get; set; }
        public string CredentialRegistryId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string Properties { get; set; }
        public Nullable<int> LifeCycleStatusTypeId { get; set; }
        public string LatestVersion { get; set; }
        public string PreviousVersion { get; set; }
        public string NextVersion { get; set; }
        public string VersionIdentifier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_HasPathway> Entity_HasPathway { get; set; }
    }
}
