//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressionModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgressionModel()
        {
            this.ProgressionModel_ProgressionLevel = new HashSet<ProgressionModel_ProgressionLevel>();
        }
    
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public int OrganizationId { get; set; }
        public int EntityStateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CTID { get; set; }
        public string Source { get; set; }
        public string CredentialRegistryId { get; set; }
        public string PublicationStatusType { get; set; }
        public string ProgressionLevels { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgressionModel_ProgressionLevel> ProgressionModel_ProgressionLevel { get; set; }
    }
}
