//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference_Framework
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reference_Framework()
        {
            this.Reference_FrameworkItem = new HashSet<Reference_FrameworkItem>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string FrameworkName { get; set; }
        public string Framework { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reference_FrameworkItem> Reference_FrameworkItem { get; set; }
    }
}
