//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubric_CriterionLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rubric_CriterionLevel()
        {
            this.Entity_HasCriterionLevel = new HashSet<Entity_HasCriterionLevel>();
        }
    
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public int RubricId { get; set; }
        public string BenchmarkLabel { get; set; }
        public string BenchmarkText { get; set; }
        public string CodedNotation { get; set; }
        public string Feedback { get; set; }
        public Nullable<bool> IsBinaryEvaluation { get; set; }
        public string ListID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> MinPercentage { get; set; }
        public Nullable<decimal> MaxPercentage { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_HasCriterionLevel> Entity_HasCriterionLevel { get; set; }
        public virtual Rubric Rubric { get; set; }
    }
}
