//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rubric()
        {
            this.Rubric_CriterionLevel = new HashSet<Rubric_CriterionLevel>();
            this.RubricCriterion = new HashSet<RubricCriterion>();
            this.RubricLevel = new HashSet<RubricLevel>();
        }
    
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int EntityStateId { get; set; }
        public string CTID { get; set; }
        public Nullable<System.Guid> PrimaryAgentUID { get; set; }
        public string SubjectWebpage { get; set; }
        public Nullable<System.Guid> Creator { get; set; }
        public string AltCodedNotation { get; set; }
        public string CodedNotation { get; set; }
        public string ConceptKeyword { get; set; }
        public Nullable<System.DateTime> DateCopyrighted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateValidFrom { get; set; }
        public Nullable<System.DateTime> DateValidUntil { get; set; }
        public string DerivedFrom { get; set; }
        public string Identifier { get; set; }
        public string InLanguage { get; set; }
        public string LatestVersion { get; set; }
        public string PreviousVersion { get; set; }
        public string NextVersion { get; set; }
        public string License { get; set; }
        public Nullable<int> LifeCycleStatusTypeId { get; set; }
        public Nullable<System.Guid> Publisher { get; set; }
        public string PublisherName { get; set; }
        public string Rights { get; set; }
        public string Subject { get; set; }
        public string VersionIdentifier { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string JsonProperties { get; set; }
        public Nullable<System.Guid> HasCriterionCategorySet { get; set; }
        public Nullable<System.Guid> HasProgressionModel { get; set; }
        public string HasScope { get; set; }
        public string HasProgressionLevel { get; set; }
        public string InCatalog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rubric_CriterionLevel> Rubric_CriterionLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RubricCriterion> RubricCriterion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RubricLevel> RubricLevel { get; set; }
    }
}
