//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchPendingReindex
    {
        public int Id { get; set; }
        public int EntityTypeId { get; set; }
        public int RecordId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> IsUpdateOrDeleteTypeId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
