//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferIntermediary_TransferValue
    {
        public int Id { get; set; }
        public int TransferIntermediaryId { get; set; }
        public int TransferValueProfileId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual TransferIntermediary TransferIntermediary { get; set; }
        public virtual TransferValueProfile TransferValueProfile { get; set; }
    }
}
