//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferIntermediary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransferIntermediary()
        {
            this.TransferIntermediary_TransferValue = new HashSet<TransferIntermediary_TransferValue>();
        }
    
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public int EntityStateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SubjectWebpage { get; set; }
        public string CTID { get; set; }
        public Nullable<System.Guid> OwningAgentUid { get; set; }
        public string LifecycleStatusType { get; set; }
        public string CredentialRegistryId { get; set; }
        public string CodedNotation { get; set; }
        public string CreditValueJson { get; set; }
        public string IntermediaryForJson { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferIntermediary_TransferValue> TransferIntermediary_TransferValue { get; set; }
    }
}
