//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferValueProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransferValueProfile()
        {
            this.Entity_TransferValueProfile = new HashSet<Entity_TransferValueProfile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int EntityStateId { get; set; }
        public string SubjectWebpage { get; set; }
        public string CTID { get; set; }
        public string CredentialRegistryId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<System.Guid> OwningAgentUid { get; set; }
        public string LifecycleStatusType { get; set; }
        public string CodedNotation { get; set; }
        public string IdentifierJson { get; set; }
        public string TransferValueJson { get; set; }
        public string TransferValueFromJson { get; set; }
        public string TransferValueForJson { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_TransferValueProfile> Entity_TransferValueProfile { get; set; }
    }
}
