//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget_Selection
    {
        public int Id { get; set; }
        public int WidgetId { get; set; }
        public string WidgetSection { get; set; }
        public int EntityTypeId { get; set; }
        public int RecordId { get; set; }
        public string ResourceName { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Widget Widget { get; set; }
    }
}
