//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIPCode2010
    {
        public int Id { get; set; }
        public string CIPFamily { get; set; }
        public string CIPCode { get; set; }
        public string Action { get; set; }
        public string TextChange { get; set; }
        public string CIPTitle { get; set; }
        public string CIPDefinition { get; set; }
        public string CrossReferences { get; set; }
        public string Examples { get; set; }
        public Nullable<int> Totals { get; set; }
        public string Url { get; set; }
    }
}
