//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes_Currency
    {
        public int NumericCode { get; set; }
        public string AlphabeticCode { get; set; }
        public string Currency { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string UnicodeDecimal { get; set; }
        public string UnicodeHex { get; set; }
        public string HtmlCodes { get; set; }
    }
}
