//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodesProperty_Counts_ByEntity
    {
        public string Entity { get; set; }
        public int EntityTypeId { get; set; }
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public string CategorySchema { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public int PropertyId { get; set; }
        public string Property { get; set; }
        public string Description { get; set; }
        public string SchemaName { get; set; }
        public Nullable<int> EntityPropertyCount { get; set; }
    }
}
