//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostProfile_SummaryForSearch
    {
        public Nullable<int> EntityBaseId { get; set; }
        public int EntityTypeId { get; set; }
        public string EntityType { get; set; }
        public int EntityId { get; set; }
        public string ParentName { get; set; }
        public Nullable<System.Guid> OwningAgentUid { get; set; }
        public int Entity_CostProfileId { get; set; }
        public string CostProfileName { get; set; }
        public System.Guid CostProfileRowId { get; set; }
        public string CostDescription { get; set; }
        public Nullable<int> CurrencyTypeId { get; set; }
        public string Currency { get; set; }
        public string CurrencySymbol { get; set; }
        public int TotalCostItems { get; set; }
        public int condProfParentEntityTypeId { get; set; }
        public int condProfParentEntityBaseId { get; set; }
    }
}
