//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential_Assets
    {
        public int CredentialEntityId { get; set; }
        public int CredentialId { get; set; }
        public int AssetTypeId { get; set; }
        public string AssetType { get; set; }
        public int AssetId { get; set; }
        public System.Guid AssetEntityUid { get; set; }
        public int AssetEntityId { get; set; }
        public string Name { get; set; }
    }
}
