//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential_Assets_AgentRelationship_Totals
    {
        public int CredentialEntityId { get; set; }
        public int CredentialId { get; set; }
        public int AssetEntityId { get; set; }
        public string EntityBaseName { get; set; }
        public int EntityTypeId { get; set; }
        public Nullable<int> EntityBaseId { get; set; }
        public System.Guid EntityUid { get; set; }
        public string EntityType { get; set; }
        public System.Guid AgentUid { get; set; }
        public string AgentName { get; set; }
        public int AgentRelativeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> QaCount { get; set; }
        public Nullable<int> OwnerCount { get; set; }
        public Nullable<int> OfferedCount { get; set; }
        public Nullable<int> RenewedCount { get; set; }
    }
}
