//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_FrameworkItemSummary
    {
        public int Id { get; set; }
        public int EntityTypeId { get; set; }
        public int EntityId { get; set; }
        public string Entity { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.Guid EntityUid { get; set; }
        public int CategoryId { get; set; }
        public string PropertyCategory { get; set; }
        public string SchemaName { get; set; }
        public int CodeId { get; set; }
        public string CodeGroup { get; set; }
        public string FrameworkCode { get; set; }
        public string FrameworkGroupTitle { get; set; }
        public string FrameworkGroup { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FrameworkGroupTitle2 { get; set; }
        public string FrameworkGroup2 { get; set; }
        public string Url2 { get; set; }
        public string URL { get; set; }
    }
}
