//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_ReferenceFramework_Summary
    {
        public int Id { get; set; }
        public int EntityId { get; set; }
        public int CategoryId { get; set; }
        public string PropertyCategory { get; set; }
        public string SchemaName { get; set; }
        public int ReferenceFrameworkId { get; set; }
        public string CodeGroup { get; set; }
        public string CodedNotation { get; set; }
        public string Name { get; set; }
        public string TargetNode { get; set; }
        public System.Guid EntityUid { get; set; }
        public string Description { get; set; }
        public int EntityTypeId { get; set; }
        public Nullable<int> EntityBaseId { get; set; }
        public Nullable<System.DateTime> refCreated { get; set; }
    }
}
