//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_AgentRelationshipIdCSV
    {
        public int EntityId { get; set; }
        public System.Guid EntityUid { get; set; }
        public Nullable<int> EntityBaseId { get; set; }
        public string EntityBaseName { get; set; }
        public string EntityType { get; set; }
        public int EntityTypeId { get; set; }
        public int AgentRelativeId { get; set; }
        public System.Guid AgentUid { get; set; }
        public string AgentName { get; set; }
        public Nullable<bool> IsInverseRole { get; set; }
        public string RoleIds { get; set; }
        public string Roles { get; set; }
        public string AgentDescription { get; set; }
        public string AgentUrl { get; set; }
        public string AgentImageUrl { get; set; }
    }
}
