//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_Subjects
    {
        public int EntityId { get; set; }
        public System.Guid EntityUid { get; set; }
        public int EntityTypeId { get; set; }
        public string SourceEntityType { get; set; }
        public string Subject { get; set; }
        public int EntitySubjectId { get; set; }
        public string Source { get; set; }
        public Nullable<int> ReferenceBaseId { get; set; }
    }
}
