//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityCompetencyFramework_Items_Summary
    {
        public int EntityId { get; set; }
        public string EntityType { get; set; }
        public string EntityName { get; set; }
        public int EntityCompetencyFrameworkItemId { get; set; }
        public string FrameworkName { get; set; }
        public string FrameworkUri { get; set; }
        public string SourceUrl { get; set; }
        public string FrameworkCtid { get; set; }
        public int EntityCompetencyId { get; set; }
        public string Competency { get; set; }
        public string TargetNodeDescription { get; set; }
        public string TargetNode { get; set; }
        public string CodedNotation { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public int EntityTypeId { get; set; }
        public Nullable<int> EntityBaseId { get; set; }
        public int ConnectionTypeId { get; set; }
        public int ConditionEntityTypeId { get; set; }
        public int ConditionEntityBaseId { get; set; }
        public Nullable<bool> ExistsInRegistry { get; set; }
        public string TargetNodeCTID { get; set; }
        public string Alignment { get; set; }
    }
}
