//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONET_SOC_JobFamily
    {
        public int JobFamilyId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Totals { get; set; }
    }
}
