//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization_Summary
    {
        public int Id { get; set; }
        public int EntityId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> EntityStateId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string SubjectWebpage { get; set; }
        public string ImageURL { get; set; }
        public System.Guid RowId { get; set; }
        public string CTID { get; set; }
        public string CredentialRegistryId { get; set; }
        public string cerEnvelopeUrl { get; set; }
        public string AvailabilityListing { get; set; }
        public int IsAQAOrganization { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int CredentialCount { get; set; }
        public int AssessmentCount { get; set; }
        public int LearningOpportunityCount { get; set; }
        public int FrameworkCount { get; set; }
        public int PathwayCount { get; set; }
        public int PathwaySetCount { get; set; }
        public int TransferValueCount { get; set; }
    }
}
