//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workIT.Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports_CredentialType
    {
        public string Name { get; set; }
        public string CTID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string SubjectWebpage { get; set; }
        public string CredentialType { get; set; }
        public Nullable<int> CredentialTypeId { get; set; }
        public string DataOwner { get; set; }
        public string DataOwnerCTID { get; set; }
        public string Publisher { get; set; }
        public string PublisherCTID { get; set; }
    }
}
